name: s1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Execute Action
        uses: ./.github/actions/s1
        with:
          Input: "Sample input"
